In [1]:
import numpy as np

In [15]:
myList = [1, 2, 3, 4, 5,6]
myArray = np.array(myList)  

In [16]:
myArray

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(0,10,5)
#(start, not inclusive, step)

array([0, 5])

In [5]:
np.zeros(5)  # creates an array of zeros with length 5

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3, 4))  # creates a 3x4 array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3,3)) # creates a 3x3 array of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0,100,20) # creates 20 evenly spaced numbers between 0 and 100

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [11]:
np.random.randn(5)  # creates an array of 5 random numbers from a standard normal distribution

array([ 0.05990731,  0.9320774 , -0.12549211, -0.20007384, -0.54981921])

In [12]:
np.random.randint(1, 10, 5)  # creates an array of 5 random integers between 1 and 10 (inclusive)

array([8, 8, 6, 6, 6])

In [14]:
np.random.seed(42)  # sets the random seed for reproducibility
np.random.rand(3, 3)  # creates a 3x3 array of random numbers between 0 and 1

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [19]:
myArray.shape  # returns the shape of the array

(6,)

In [20]:
myArray.size  # returns the total number of elements in the array

6

In [25]:
myArray = myArray.reshape(2,3)  # reshapes the array to 2 rows and 3 columns
myArray

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
myArray.shape

(2, 3)

In [ ]:
print(myArray.min())  # returns the minimum value in the array
print(myArray.max())  # returns the maximum value in the array
print(myArray.argmax())  # returns the index of the maximum value in the array according to the flattened array index

1
6
5
